/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export interface CartItem {
  'productId' : bigint,
  'addedAt' : bigint,
  'quantity' : bigint,
}
export interface CartPublic {
  'userId' : Principal,
  'updatedAt' : bigint,
  'items' : Array<CartItem>,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
  'description' : string,
  'imageUrl' : string,
  'subCategories' : Array<SubCategory>,
}
export type CategoryId = bigint;
export interface CreateOrderInput {
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : string,
  'deliveryCost' : bigint,
  'deliveryType' : DeliveryType,
  'items' : Array<{ 'productId' : bigint, 'quantity' : bigint }>,
}
export interface CreateServiceRequestInput {
  'userName' : string,
  'serviceType' : ServiceType,
  'recipientPhone' : [] | [string],
  'description' : string,
  'userPhone' : string,
  'isRequestForSelf' : boolean,
  'preferredDate' : string,
  'preferredTime' : string,
  'recipientAddress' : [] | [string],
  'recipientName' : [] | [string],
}
export interface CustomerReview {
  'id' : CustomerReviewId,
  'createdAt' : bigint,
  'reviewText' : string,
  'reviewerName' : string,
  'productName' : string,
  'rating' : bigint,
}
export type CustomerReviewId = bigint;
export interface DeliveryAddress {
  'street' : string,
  'city' : string,
  'name' : string,
  'district' : string,
  'state' : string,
  'landmark' : string,
  'phone' : string,
  'pincode' : string,
  'locality' : string,
  'houseNo' : string,
}
export type DeliveryType = { 'Standard' : null } |
  { 'Express' : null };
export interface FeaturedBlock {
  'id' : FeaturedBlockId,
  'title' : string,
  'content' : string,
  'thumbnailUrl' : string,
  'order' : bigint,
  'createdAt' : bigint,
  'isActive' : boolean,
  'contentImages' : Array<string>,
}
export type FeaturedBlockId = bigint;
export interface FeaturedBlockInput {
  'title' : string,
  'content' : string,
  'thumbnailUrl' : string,
  'order' : bigint,
  'isActive' : boolean,
  'contentImages' : Array<string>,
}
export interface HeroBanner {
  'id' : HeroBannerId,
  'title' : string,
  'order' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
  'ctaSlug' : string,
  'ctaText' : string,
  'durationSeconds' : bigint,
  'subtitle' : string,
}
export type HeroBannerId = bigint;
export interface HeroBannerInput {
  'title' : string,
  'order' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
  'ctaSlug' : string,
  'ctaText' : string,
  'durationSeconds' : bigint,
  'subtitle' : string,
}
export interface HowItWorksStep { 'title' : string, 'description' : string }
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'discountPercent' : bigint,
  'productId' : bigint,
  'imageUrl' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'shipmentUpdates' : Array<ShipmentUpdate>,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'estimatedDelivery' : [] | [bigint],
  'deliveryCost' : bigint,
  'deliveryType' : DeliveryType,
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'OutForDelivery' : null };
export interface Product {
  'id' : ProductId,
  'subCategory' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'stock' : bigint,
  'category' : CategoryId,
  'brand' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'inStockOnly' : boolean,
  'offset' : bigint,
  'maxPrice' : [] | [bigint],
  'limit' : bigint,
  'searchTerm' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export interface ProductInput {
  'subCategory' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'stock' : bigint,
  'category' : CategoryId,
  'brand' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductListResult {
  'total' : bigint,
  'products' : Array<Product>,
}
export interface ServiceRequestPublic {
  'id' : bigint,
  'status' : ServiceRequestStatus,
  'userName' : string,
  'serviceType' : ServiceType,
  'userId' : string,
  'recipientPhone' : [] | [string],
  'submittedAt' : bigint,
  'description' : string,
  'userPhone' : string,
  'lastUpdatedAt' : bigint,
  'isRequestForSelf' : boolean,
  'preferredDate' : string,
  'preferredTime' : string,
  'recipientAddress' : [] | [string],
  'recipientName' : [] | [string],
}
export type ServiceRequestStatus = { 'New' : null } |
  { 'Contacted' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export type ServiceType = { 'Ambulance' : null } |
  { 'FoodDelivery' : null } |
  { 'Taxi' : null } |
  { 'SchoolAdmissions' : null } |
  { 'Medicines' : null } |
  { 'Gifting' : null } |
  { 'FuneralServices' : null } |
  { 'Tourism' : null } |
  { 'Doctors' : null } |
  { 'VideoConferencing' : null } |
  { 'EventManagement' : null } |
  { 'WeddingsAnniversaries' : null } |
  { 'Other' : null };
export interface ShipmentUpdate {
  'status' : OrderStatus,
  'message' : string,
  'timestamp' : bigint,
}
export interface SocialLink {
  'url' : string,
  'platform' : string,
  'enabled' : boolean,
}
export interface SubCategory {
  'id' : SubCategoryId,
  'name' : string,
  'imageUrl' : string,
}
export type SubCategoryId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfileInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'addresses' : Array<Address>,
  'isAdmin' : boolean,
  'phone' : string,
}
export interface VendorOrderSummary {
  'productId' : string,
  'productName' : string,
  'orderId' : string,
  'placedAt' : bigint,
  'quantity' : bigint,
  'totalPrice' : number,
}
export interface VendorProductInput {
  'moq' : [] | [bigint],
  'mrp' : [] | [bigint],
  'imageUrls' : Array<string>,
  'fssaiDocumentUrl' : [] | [string],
  'pricePerKg' : [] | [bigint],
  'supplyPrice' : [] | [bigint],
  'description' : string,
  'productName' : string,
  'availableQuantityKg' : [] | [bigint],
  'category' : string,
  'basePrice' : bigint,
  'vendorName' : string,
  'vendorType' : VendorType,
}
export interface VendorProductView {
  'id' : bigint,
  'moq' : [] | [bigint],
  'mrp' : [] | [bigint],
  'finalPrice' : [] | [bigint],
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'packagingCost' : [] | [bigint],
  'taxPercent' : [] | [bigint],
  'imageUrls' : Array<string>,
  'fssaiDocumentUrl' : [] | [string],
  'pricePerKg' : [] | [bigint],
  'rejectionReason' : [] | [string],
  'supplyPrice' : [] | [bigint],
  'submittedAt' : bigint,
  'description' : string,
  'productName' : string,
  'reviewedAt' : [] | [bigint],
  'availableQuantityKg' : [] | [bigint],
  'vendorId' : Principal,
  'category' : string,
  'basePrice' : bigint,
  'vendorEmail' : string,
  'vendorName' : string,
  'vendorType' : VendorType,
}
export interface VendorProfile {
  'id' : Principal,
  'bankAccountNumber' : string,
  'categories' : Array<string>,
  'status' : VendorStatus,
  'assignedProductIds' : Array<string>,
  'ifscCode' : string,
  'fssaiDocumentUrl' : [] | [string],
  'approvedAt' : [] | [bigint],
  'businessName' : string,
  'address' : string,
  'contactEmail' : string,
  'brandName' : [] | [string],
  'phone' : string,
  'packagingDetails' : [] | [string],
  'registeredAt' : bigint,
  'vendorType' : VendorType,
  'gstinNumber' : [] | [string],
}
export interface VendorRegistration {
  'bankAccountNumber' : string,
  'categories' : Array<string>,
  'ifscCode' : string,
  'fssaiDocumentUrl' : [] | [string],
  'businessName' : string,
  'address' : string,
  'contactEmail' : string,
  'brandName' : [] | [string],
  'phone' : string,
  'packagingDetails' : [] | [string],
  'vendorType' : VendorType,
  'gstinNumber' : [] | [string],
}
export type VendorStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface VendorSummary {
  'id' : Principal,
  'bankAccountNumber' : string,
  'categories' : Array<string>,
  'status' : VendorStatus,
  'assignedProductIds' : Array<string>,
  'ifscCode' : string,
  'fssaiDocumentUrl' : [] | [string],
  'approvedAt' : [] | [bigint],
  'businessName' : string,
  'address' : string,
  'contactEmail' : string,
  'brandName' : [] | [string],
  'phone' : string,
  'packagingDetails' : [] | [string],
  'registeredAt' : bigint,
  'vendorType' : VendorType,
  'gstinNumber' : [] | [string],
}
export type VendorType = { 'rawMaterial' : null } |
  { 'brand' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMyAddress' : ActorMethod<[Address], UserProfilePublic>,
  'addToCart' : ActorMethod<[bigint, bigint], CartPublic>,
  'adminAddCategory' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'adminAddFeaturedBlock' : ActorMethod<
    [string, FeaturedBlockInput],
    FeaturedBlock
  >,
  'adminAddHeroBanner' : ActorMethod<[string, HeroBannerInput], HeroBanner>,
  'adminAddProduct' : ActorMethod<[string, ProductInput], Product>,
  'adminAddReview' : ActorMethod<
    [string, string, bigint, string, string],
    bigint
  >,
  'adminAddSubCategory' : ActorMethod<
    [string, CategoryId, string, string],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'adminApproveVendor' : ActorMethod<
    [string, Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveVendorProduct' : ActorMethod<
    [string, bigint, bigint, [] | [bigint]],
    { 'ok' : VendorProductView } |
      { 'err' : string }
  >,
  'adminAssignProductToVendor' : ActorMethod<
    [string, Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteCategory' : ActorMethod<
    [string, CategoryId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminDeleteFeaturedBlock' : ActorMethod<
    [string, FeaturedBlockId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminDeleteHeroBanner' : ActorMethod<
    [string, HeroBannerId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminDeleteProduct' : ActorMethod<[string, ProductId], boolean>,
  'adminDeleteReview' : ActorMethod<[string, bigint], boolean>,
  'adminDeleteServiceRequest' : ActorMethod<[string, bigint], boolean>,
  'adminDeleteSubCategory' : ActorMethod<
    [string, CategoryId, SubCategoryId],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'adminGetAllOrders' : ActorMethod<[bigint, bigint], Array<OrderPublic>>,
  'adminGetCategories' : ActorMethod<[string], Array<Category>>,
  'adminGetServiceRequests' : ActorMethod<
    [string],
    Array<ServiceRequestPublic>
  >,
  'adminListFeaturedBlocks' : ActorMethod<[string], Array<FeaturedBlock>>,
  'adminListHeroBanners' : ActorMethod<[string], Array<HeroBanner>>,
  'adminListVendorProducts' : ActorMethod<[string], Array<VendorProductView>>,
  'adminListVendorProductsByVendor' : ActorMethod<
    [string, Principal],
    Array<VendorProductView>
  >,
  'adminListVendors' : ActorMethod<[[] | [VendorStatus]], Array<VendorSummary>>,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'adminRegisterImageHash' : ActorMethod<[string, string], string>,
  'adminRejectVendor' : ActorMethod<
    [string, Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectVendorProduct' : ActorMethod<
    [string, bigint, string],
    { 'ok' : VendorProductView } |
      { 'err' : string }
  >,
  'adminReorderHeroBanner' : ActorMethod<
    [string, HeroBannerId, bigint],
    { 'ok' : HeroBanner } |
      { 'err' : string }
  >,
  'adminRequestOtp' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'adminSetDiscount' : ActorMethod<[string, ProductId, bigint], [] | [Product]>,
  'adminSetUserAdmin' : ActorMethod<[Principal, boolean], boolean>,
  'adminSuspendVendor' : ActorMethod<
    [string, Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUnassignProductFromVendor' : ActorMethod<
    [string, Principal, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateCategory' : ActorMethod<
    [string, CategoryId, string, string, string, string],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'adminUpdateFeaturedBlock' : ActorMethod<
    [string, FeaturedBlockId, FeaturedBlockInput],
    { 'ok' : FeaturedBlock } |
      { 'err' : string }
  >,
  'adminUpdateFooterSettings' : ActorMethod<
    [string, string, string, string, Array<SocialLink>],
    boolean
  >,
  'adminUpdateHeroAndHowitworks' : ActorMethod<
    [string, string, string, Array<HowItWorksStep>],
    undefined
  >,
  'adminUpdateHeroBanner' : ActorMethod<
    [string, HeroBannerId, HeroBannerInput],
    { 'ok' : HeroBanner } |
      { 'err' : string }
  >,
  'adminUpdateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus, string],
    [] | [OrderPublic]
  >,
  'adminUpdatePolicyContent' : ActorMethod<[string, string], boolean>,
  'adminUpdateProduct' : ActorMethod<
    [string, ProductId, ProductInput],
    [] | [Product]
  >,
  'adminUpdateReview' : ActorMethod<
    [string, bigint, string, bigint, string, string],
    boolean
  >,
  'adminUpdateServiceRequestStatus' : ActorMethod<
    [string, bigint, ServiceRequestStatus],
    [] | [ServiceRequestPublic]
  >,
  'adminUpdateServicesAvailability' : ActorMethod<
    [string, boolean, string],
    undefined
  >,
  'adminUpdateSiteSettings' : ActorMethod<
    [string, [] | [string], [] | [string]],
    { 'logoUrl' : [] | [string], 'faviconUrl' : [] | [string] }
  >,
  'adminUpdateStock' : ActorMethod<[string, ProductId, bigint], [] | [Product]>,
  'adminUpdateSubCategory' : ActorMethod<
    [string, CategoryId, SubCategoryId, string, string],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'adminUpdateVendorProductQuantity' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateVideoByte' : ActorMethod<
    [string, string, boolean, string],
    undefined
  >,
  'adminVerifyKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminVerifyOtp' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'claimAdminIfFirst' : ActorMethod<[], boolean>,
  'clearMyCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[CreateOrderInput], OrderPublic>,
  'createRazorpayOrder' : ActorMethod<
    [bigint, string],
    { 'ok' : { 'orderId' : string, 'currency' : string, 'amount' : bigint } } |
      { 'err' : string }
  >,
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  'getCategoryBySlug' : ActorMethod<[string], [] | [Category]>,
  'getFeaturedBlock' : ActorMethod<[FeaturedBlockId], [] | [FeaturedBlock]>,
  'getFooterSettings' : ActorMethod<
    [],
    {
      'tagline' : string,
      'socialLinks' : Array<SocialLink>,
      'policyContent' : string,
      'aboutContent' : string,
      'copyright' : string,
    }
  >,
  'getHeroBanner' : ActorMethod<[HeroBannerId], [] | [HeroBanner]>,
  'getMyCart' : ActorMethod<[], CartPublic>,
  'getMyOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getMyProfile' : ActorMethod<[], UserProfilePublic>,
  'getMyVendorOrders' : ActorMethod<[], Array<VendorOrderSummary>>,
  'getMyVendorProfile' : ActorMethod<
    [],
    { 'ok' : VendorProfile } |
      { 'err' : string }
  >,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getReviews' : ActorMethod<[], Array<CustomerReview>>,
  'getServicesAvailability' : ActorMethod<
    [],
    { 'available' : boolean, 'message' : string }
  >,
  'getSiteSettings' : ActorMethod<
    [],
    {
      'heroSubtitle' : string,
      'howitworksSteps' : Array<HowItWorksStep>,
      'logoUrl' : [] | [string],
      'faviconUrl' : [] | [string],
      'heroTagline' : string,
    }
  >,
  'getVendorForProduct' : ActorMethod<[string], [] | [VendorSummary]>,
  'getVendorStatusBySession' : ActorMethod<[string], [] | [VendorStatus]>,
  'getVideoByte' : ActorMethod<
    [],
    { 'url' : string, 'title' : string, 'enabled' : boolean }
  >,
  'isAdminSession' : ActorMethod<[string], boolean>,
  'isCurrentUserAdmin' : ActorMethod<[], boolean>,
  'listBestSellers' : ActorMethod<[bigint], Array<Product>>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listFeaturedBlocks' : ActorMethod<[], Array<FeaturedBlock>>,
  'listHeroBanners' : ActorMethod<[], Array<HeroBanner>>,
  'listNewArrivals' : ActorMethod<[bigint], Array<Product>>,
  'listProducts' : ActorMethod<[ProductFilter], ProductListResult>,
  'listProductsByCategory' : ActorMethod<
    [CategoryId, bigint, bigint],
    ProductListResult
  >,
  'processVendorActionToken' : ActorMethod<
    [string, { 'reject' : null } | { 'approve' : null }],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'razorpayTransform' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'registerVendor' : ActorMethod<
    [VendorRegistration],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeFromCart' : ActorMethod<[bigint], CartPublic>,
  'requestOtp' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'searchProducts' : ActorMethod<[string, bigint, bigint], ProductListResult>,
  'submitServiceRequest' : ActorMethod<
    [CreateServiceRequestInput],
    ServiceRequestPublic
  >,
  'updateCartItem' : ActorMethod<[bigint, bigint], CartPublic>,
  'updateMyProfile' : ActorMethod<[UserProfileInput], UserProfilePublic>,
  'vendorGetMyProducts' : ActorMethod<
    [string],
    { 'ok' : Array<VendorProductView> } |
      { 'err' : string }
  >,
  'vendorSubmitProduct' : ActorMethod<
    [string, VendorProductInput],
    { 'ok' : VendorProductView } |
      { 'err' : string }
  >,
  'vendorUpdateProductQuantity' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyOtp' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifyRazorpayPayment' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'verifyVendorOtp' : ActorMethod<
    [string, string],
    { 'ok' : { 'status' : VendorStatus, 'token' : string } } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];