/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserId = IDL.Principal;
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'addresses' : IDL.Vec(Address),
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'addedAt' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const CartPublic = IDL.Record({
  'userId' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});
export const CategoryId = IDL.Nat;
export const SubCategoryId = IDL.Nat;
export const SubCategory = IDL.Record({
  'id' : SubCategoryId,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'subCategories' : IDL.Vec(SubCategory),
});
export const FeaturedBlockInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'contentImages' : IDL.Vec(IDL.Text),
});
export const FeaturedBlockId = IDL.Nat;
export const FeaturedBlock = IDL.Record({
  'id' : FeaturedBlockId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Nat,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'contentImages' : IDL.Vec(IDL.Text),
});
export const HeroBannerInput = IDL.Record({
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'ctaSlug' : IDL.Text,
  'ctaText' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'subtitle' : IDL.Text,
});
export const HeroBannerId = IDL.Nat;
export const HeroBanner = IDL.Record({
  'id' : HeroBannerId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'ctaSlug' : IDL.Text,
  'ctaText' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'subtitle' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'subCategory' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'stock' : IDL.Nat,
  'category' : CategoryId,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'subCategory' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'stock' : IDL.Nat,
  'category' : CategoryId,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const VendorType = IDL.Variant({
  'rawMaterial' : IDL.Null,
  'brand' : IDL.Null,
});
export const VendorProductView = IDL.Record({
  'id' : IDL.Nat,
  'moq' : IDL.Opt(IDL.Nat),
  'mrp' : IDL.Opt(IDL.Nat),
  'finalPrice' : IDL.Opt(IDL.Nat),
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'packagingCost' : IDL.Opt(IDL.Nat),
  'taxPercent' : IDL.Opt(IDL.Nat),
  'imageUrls' : IDL.Vec(IDL.Text),
  'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
  'pricePerKg' : IDL.Opt(IDL.Nat),
  'rejectionReason' : IDL.Opt(IDL.Text),
  'supplyPrice' : IDL.Opt(IDL.Nat),
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'productName' : IDL.Text,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'availableQuantityKg' : IDL.Opt(IDL.Nat),
  'vendorId' : IDL.Principal,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
  'vendorEmail' : IDL.Text,
  'vendorName' : IDL.Text,
  'vendorType' : VendorType,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'OutForDelivery' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'landmark' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'locality' : IDL.Text,
  'houseNo' : IDL.Text,
});
export const ShipmentUpdate = IDL.Record({
  'status' : OrderStatus,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DeliveryType = IDL.Variant({
  'Standard' : IDL.Null,
  'Express' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'productId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'shipmentUpdates' : IDL.Vec(ShipmentUpdate),
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'estimatedDelivery' : IDL.Opt(IDL.Int),
  'deliveryCost' : IDL.Nat,
  'deliveryType' : DeliveryType,
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const ServiceRequestStatus = IDL.Variant({
  'New' : IDL.Null,
  'Contacted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'Ambulance' : IDL.Null,
  'FoodDelivery' : IDL.Null,
  'Taxi' : IDL.Null,
  'SchoolAdmissions' : IDL.Null,
  'Medicines' : IDL.Null,
  'Gifting' : IDL.Null,
  'FuneralServices' : IDL.Null,
  'Tourism' : IDL.Null,
  'Doctors' : IDL.Null,
  'VideoConferencing' : IDL.Null,
  'EventManagement' : IDL.Null,
  'WeddingsAnniversaries' : IDL.Null,
  'Other' : IDL.Null,
});
export const ServiceRequestPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ServiceRequestStatus,
  'userName' : IDL.Text,
  'serviceType' : ServiceType,
  'userId' : IDL.Text,
  'recipientPhone' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'userPhone' : IDL.Text,
  'lastUpdatedAt' : IDL.Int,
  'isRequestForSelf' : IDL.Bool,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'recipientAddress' : IDL.Opt(IDL.Text),
  'recipientName' : IDL.Opt(IDL.Text),
});
export const VendorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const VendorSummary = IDL.Record({
  'id' : IDL.Principal,
  'bankAccountNumber' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'status' : VendorStatus,
  'assignedProductIds' : IDL.Vec(IDL.Text),
  'ifscCode' : IDL.Text,
  'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
  'approvedAt' : IDL.Opt(IDL.Int),
  'businessName' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'brandName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'packagingDetails' : IDL.Opt(IDL.Text),
  'registeredAt' : IDL.Int,
  'vendorType' : VendorType,
  'gstinNumber' : IDL.Opt(IDL.Text),
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const HowItWorksStep = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : IDL.Text,
  'deliveryCost' : IDL.Nat,
  'deliveryType' : DeliveryType,
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
});
export const VendorOrderSummary = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'placedAt' : IDL.Int,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Float64,
});
export const VendorProfile = IDL.Record({
  'id' : IDL.Principal,
  'bankAccountNumber' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'status' : VendorStatus,
  'assignedProductIds' : IDL.Vec(IDL.Text),
  'ifscCode' : IDL.Text,
  'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
  'approvedAt' : IDL.Opt(IDL.Int),
  'businessName' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'brandName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'packagingDetails' : IDL.Opt(IDL.Text),
  'registeredAt' : IDL.Int,
  'vendorType' : VendorType,
  'gstinNumber' : IDL.Opt(IDL.Text),
});
export const CustomerReviewId = IDL.Nat;
export const CustomerReview = IDL.Record({
  'id' : CustomerReviewId,
  'createdAt' : IDL.Int,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'productName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'inStockOnly' : IDL.Bool,
  'offset' : IDL.Nat,
  'maxPrice' : IDL.Opt(IDL.Nat),
  'limit' : IDL.Nat,
  'searchTerm' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const ProductListResult = IDL.Record({
  'total' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const VendorRegistration = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'ifscCode' : IDL.Text,
  'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
  'businessName' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'brandName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'packagingDetails' : IDL.Opt(IDL.Text),
  'vendorType' : VendorType,
  'gstinNumber' : IDL.Opt(IDL.Text),
});
export const CreateServiceRequestInput = IDL.Record({
  'userName' : IDL.Text,
  'serviceType' : ServiceType,
  'recipientPhone' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'userPhone' : IDL.Text,
  'isRequestForSelf' : IDL.Bool,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'recipientAddress' : IDL.Opt(IDL.Text),
  'recipientName' : IDL.Opt(IDL.Text),
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const VendorProductInput = IDL.Record({
  'moq' : IDL.Opt(IDL.Nat),
  'mrp' : IDL.Opt(IDL.Nat),
  'imageUrls' : IDL.Vec(IDL.Text),
  'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
  'pricePerKg' : IDL.Opt(IDL.Nat),
  'supplyPrice' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'productName' : IDL.Text,
  'availableQuantityKg' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
  'vendorName' : IDL.Text,
  'vendorType' : VendorType,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMyAddress' : IDL.Func([Address], [UserProfilePublic], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
  'adminAddCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
      [],
    ),
  'adminAddFeaturedBlock' : IDL.Func(
      [IDL.Text, FeaturedBlockInput],
      [FeaturedBlock],
      [],
    ),
  'adminAddHeroBanner' : IDL.Func(
      [IDL.Text, HeroBannerInput],
      [HeroBanner],
      [],
    ),
  'adminAddProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
  'adminAddReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminAddSubCategory' : IDL.Func(
      [IDL.Text, CategoryId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveVendor' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveVendorProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
      [],
    ),
  'adminAssignProductToVendor' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteCategory' : IDL.Func(
      [IDL.Text, CategoryId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteFeaturedBlock' : IDL.Func(
      [IDL.Text, FeaturedBlockId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteHeroBanner' : IDL.Func(
      [IDL.Text, HeroBannerId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
  'adminDeleteReview' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'adminDeleteServiceRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'adminDeleteSubCategory' : IDL.Func(
      [IDL.Text, CategoryId, SubCategoryId],
      [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllOrders' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'adminGetCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
  'adminGetServiceRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceRequestPublic)],
      ['query'],
    ),
  'adminListFeaturedBlocks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeaturedBlock)],
      ['query'],
    ),
  'adminListHeroBanners' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HeroBanner)],
      ['query'],
    ),
  'adminListVendorProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VendorProductView)],
      ['query'],
    ),
  'adminListVendorProductsByVendor' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Vec(VendorProductView)],
      ['query'],
    ),
  'adminListVendors' : IDL.Func(
      [IDL.Opt(VendorStatus)],
      [IDL.Vec(VendorSummary)],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'adminRegisterImageHash' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminRejectVendor' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectVendorProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
      [],
    ),
  'adminReorderHeroBanner' : IDL.Func(
      [IDL.Text, HeroBannerId, IDL.Nat],
      [IDL.Variant({ 'ok' : HeroBanner, 'err' : IDL.Text })],
      [],
    ),
  'adminRequestOtp' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetDiscount' : IDL.Func(
      [IDL.Text, ProductId, IDL.Nat],
      [IDL.Opt(Product)],
      [],
    ),
  'adminSetUserAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'adminSuspendVendor' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUnassignProductFromVendor' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateCategory' : IDL.Func(
      [IDL.Text, CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateFeaturedBlock' : IDL.Func(
      [IDL.Text, FeaturedBlockId, FeaturedBlockInput],
      [IDL.Variant({ 'ok' : FeaturedBlock, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateFooterSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
      [IDL.Bool],
      [],
    ),
  'adminUpdateHeroAndHowitworks' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(HowItWorksStep)],
      [],
      [],
    ),
  'adminUpdateHeroBanner' : IDL.Func(
      [IDL.Text, HeroBannerId, HeroBannerInput],
      [IDL.Variant({ 'ok' : HeroBanner, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus, IDL.Text],
      [IDL.Opt(OrderPublic)],
      [],
    ),
  'adminUpdatePolicyContent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminUpdateProduct' : IDL.Func(
      [IDL.Text, ProductId, ProductInput],
      [IDL.Opt(Product)],
      [],
    ),
  'adminUpdateReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminUpdateServiceRequestStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, ServiceRequestStatus],
      [IDL.Opt(ServiceRequestPublic)],
      [],
    ),
  'adminUpdateServicesAvailability' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'adminUpdateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'logoUrl' : IDL.Opt(IDL.Text),
          'faviconUrl' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'adminUpdateStock' : IDL.Func(
      [IDL.Text, ProductId, IDL.Nat],
      [IDL.Opt(Product)],
      [],
    ),
  'adminUpdateSubCategory' : IDL.Func(
      [IDL.Text, CategoryId, SubCategoryId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateVendorProductQuantity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateVideoByte' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'adminVerifyKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminVerifyOtp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
  'clearMyCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'orderId' : IDL.Text,
            'currency' : IDL.Text,
            'amount' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getCategoryBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getFeaturedBlock' : IDL.Func(
      [FeaturedBlockId],
      [IDL.Opt(FeaturedBlock)],
      ['query'],
    ),
  'getFooterSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'tagline' : IDL.Text,
          'socialLinks' : IDL.Vec(SocialLink),
          'policyContent' : IDL.Text,
          'aboutContent' : IDL.Text,
          'copyright' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getHeroBanner' : IDL.Func([HeroBannerId], [IDL.Opt(HeroBanner)], ['query']),
  'getMyCart' : IDL.Func([], [CartPublic], []),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfilePublic], []),
  'getMyVendorOrders' : IDL.Func([], [IDL.Vec(VendorOrderSummary)], ['query']),
  'getMyVendorProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : VendorProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
  'getServicesAvailability' : IDL.Func(
      [],
      [IDL.Record({ 'available' : IDL.Bool, 'message' : IDL.Text })],
      ['query'],
    ),
  'getSiteSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'heroSubtitle' : IDL.Text,
          'howitworksSteps' : IDL.Vec(HowItWorksStep),
          'logoUrl' : IDL.Opt(IDL.Text),
          'faviconUrl' : IDL.Opt(IDL.Text),
          'heroTagline' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getVendorForProduct' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VendorSummary)],
      ['query'],
    ),
  'getVendorStatusBySession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VendorStatus)],
      ['query'],
    ),
  'getVideoByte' : IDL.Func(
      [],
      [
        IDL.Record({
          'url' : IDL.Text,
          'title' : IDL.Text,
          'enabled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBestSellers' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listFeaturedBlocks' : IDL.Func([], [IDL.Vec(FeaturedBlock)], ['query']),
  'listHeroBanners' : IDL.Func([], [IDL.Vec(HeroBanner)], ['query']),
  'listNewArrivals' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [ProductListResult], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId, IDL.Nat, IDL.Nat],
      [ProductListResult],
      ['query'],
    ),
  'processVendorActionToken' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'reject' : IDL.Null, 'approve' : IDL.Null })],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'razorpayTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'registerVendor' : IDL.Func(
      [VendorRegistration],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Nat], [CartPublic], []),
  'requestOtp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [ProductListResult],
      ['query'],
    ),
  'submitServiceRequest' : IDL.Func(
      [CreateServiceRequestInput],
      [ServiceRequestPublic],
      [],
    ),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
  'updateMyProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
  'vendorGetMyProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(VendorProductView), 'err' : IDL.Text })],
      [],
    ),
  'vendorSubmitProduct' : IDL.Func(
      [IDL.Text, VendorProductInput],
      [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
      [],
    ),
  'vendorUpdateProductQuantity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'verifyVendorOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'status' : VendorStatus, 'token' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'addresses' : IDL.Vec(Address),
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'addedAt' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const CartPublic = IDL.Record({
    'userId' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  const CategoryId = IDL.Nat;
  const SubCategoryId = IDL.Nat;
  const SubCategory = IDL.Record({
    'id' : SubCategoryId,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'subCategories' : IDL.Vec(SubCategory),
  });
  const FeaturedBlockInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'contentImages' : IDL.Vec(IDL.Text),
  });
  const FeaturedBlockId = IDL.Nat;
  const FeaturedBlock = IDL.Record({
    'id' : FeaturedBlockId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'contentImages' : IDL.Vec(IDL.Text),
  });
  const HeroBannerInput = IDL.Record({
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'ctaSlug' : IDL.Text,
    'ctaText' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'subtitle' : IDL.Text,
  });
  const HeroBannerId = IDL.Nat;
  const HeroBanner = IDL.Record({
    'id' : HeroBannerId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'ctaSlug' : IDL.Text,
    'ctaText' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'subtitle' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'subCategory' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'stock' : IDL.Nat,
    'category' : CategoryId,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'subCategory' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'stock' : IDL.Nat,
    'category' : CategoryId,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const VendorType = IDL.Variant({
    'rawMaterial' : IDL.Null,
    'brand' : IDL.Null,
  });
  const VendorProductView = IDL.Record({
    'id' : IDL.Nat,
    'moq' : IDL.Opt(IDL.Nat),
    'mrp' : IDL.Opt(IDL.Nat),
    'finalPrice' : IDL.Opt(IDL.Nat),
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'packagingCost' : IDL.Opt(IDL.Nat),
    'taxPercent' : IDL.Opt(IDL.Nat),
    'imageUrls' : IDL.Vec(IDL.Text),
    'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
    'pricePerKg' : IDL.Opt(IDL.Nat),
    'rejectionReason' : IDL.Opt(IDL.Text),
    'supplyPrice' : IDL.Opt(IDL.Nat),
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'productName' : IDL.Text,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'availableQuantityKg' : IDL.Opt(IDL.Nat),
    'vendorId' : IDL.Principal,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
    'vendorEmail' : IDL.Text,
    'vendorName' : IDL.Text,
    'vendorType' : VendorType,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'OutForDelivery' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'landmark' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'locality' : IDL.Text,
    'houseNo' : IDL.Text,
  });
  const ShipmentUpdate = IDL.Record({
    'status' : OrderStatus,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DeliveryType = IDL.Variant({
    'Standard' : IDL.Null,
    'Express' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'productId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'shipmentUpdates' : IDL.Vec(ShipmentUpdate),
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'estimatedDelivery' : IDL.Opt(IDL.Int),
    'deliveryCost' : IDL.Nat,
    'deliveryType' : DeliveryType,
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const ServiceRequestStatus = IDL.Variant({
    'New' : IDL.Null,
    'Contacted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'Ambulance' : IDL.Null,
    'FoodDelivery' : IDL.Null,
    'Taxi' : IDL.Null,
    'SchoolAdmissions' : IDL.Null,
    'Medicines' : IDL.Null,
    'Gifting' : IDL.Null,
    'FuneralServices' : IDL.Null,
    'Tourism' : IDL.Null,
    'Doctors' : IDL.Null,
    'VideoConferencing' : IDL.Null,
    'EventManagement' : IDL.Null,
    'WeddingsAnniversaries' : IDL.Null,
    'Other' : IDL.Null,
  });
  const ServiceRequestPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ServiceRequestStatus,
    'userName' : IDL.Text,
    'serviceType' : ServiceType,
    'userId' : IDL.Text,
    'recipientPhone' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'userPhone' : IDL.Text,
    'lastUpdatedAt' : IDL.Int,
    'isRequestForSelf' : IDL.Bool,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'recipientAddress' : IDL.Opt(IDL.Text),
    'recipientName' : IDL.Opt(IDL.Text),
  });
  const VendorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const VendorSummary = IDL.Record({
    'id' : IDL.Principal,
    'bankAccountNumber' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'status' : VendorStatus,
    'assignedProductIds' : IDL.Vec(IDL.Text),
    'ifscCode' : IDL.Text,
    'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
    'approvedAt' : IDL.Opt(IDL.Int),
    'businessName' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'brandName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'packagingDetails' : IDL.Opt(IDL.Text),
    'registeredAt' : IDL.Int,
    'vendorType' : VendorType,
    'gstinNumber' : IDL.Opt(IDL.Text),
  });
  const SocialLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const HowItWorksStep = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'deliveryAddress' : DeliveryAddress,
    'paymentMethod' : IDL.Text,
    'deliveryCost' : IDL.Nat,
    'deliveryType' : DeliveryType,
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
  });
  const VendorOrderSummary = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'placedAt' : IDL.Int,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Float64,
  });
  const VendorProfile = IDL.Record({
    'id' : IDL.Principal,
    'bankAccountNumber' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'status' : VendorStatus,
    'assignedProductIds' : IDL.Vec(IDL.Text),
    'ifscCode' : IDL.Text,
    'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
    'approvedAt' : IDL.Opt(IDL.Int),
    'businessName' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'brandName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'packagingDetails' : IDL.Opt(IDL.Text),
    'registeredAt' : IDL.Int,
    'vendorType' : VendorType,
    'gstinNumber' : IDL.Opt(IDL.Text),
  });
  const CustomerReviewId = IDL.Nat;
  const CustomerReview = IDL.Record({
    'id' : CustomerReviewId,
    'createdAt' : IDL.Int,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'productName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'inStockOnly' : IDL.Bool,
    'offset' : IDL.Nat,
    'maxPrice' : IDL.Opt(IDL.Nat),
    'limit' : IDL.Nat,
    'searchTerm' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const ProductListResult = IDL.Record({
    'total' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const VendorRegistration = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'ifscCode' : IDL.Text,
    'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
    'businessName' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'brandName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'packagingDetails' : IDL.Opt(IDL.Text),
    'vendorType' : VendorType,
    'gstinNumber' : IDL.Opt(IDL.Text),
  });
  const CreateServiceRequestInput = IDL.Record({
    'userName' : IDL.Text,
    'serviceType' : ServiceType,
    'recipientPhone' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'userPhone' : IDL.Text,
    'isRequestForSelf' : IDL.Bool,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'recipientAddress' : IDL.Opt(IDL.Text),
    'recipientName' : IDL.Opt(IDL.Text),
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VendorProductInput = IDL.Record({
    'moq' : IDL.Opt(IDL.Nat),
    'mrp' : IDL.Opt(IDL.Nat),
    'imageUrls' : IDL.Vec(IDL.Text),
    'fssaiDocumentUrl' : IDL.Opt(IDL.Text),
    'pricePerKg' : IDL.Opt(IDL.Nat),
    'supplyPrice' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'productName' : IDL.Text,
    'availableQuantityKg' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
    'vendorName' : IDL.Text,
    'vendorType' : VendorType,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMyAddress' : IDL.Func([Address], [UserProfilePublic], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
    'adminAddCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
        [],
      ),
    'adminAddFeaturedBlock' : IDL.Func(
        [IDL.Text, FeaturedBlockInput],
        [FeaturedBlock],
        [],
      ),
    'adminAddHeroBanner' : IDL.Func(
        [IDL.Text, HeroBannerInput],
        [HeroBanner],
        [],
      ),
    'adminAddProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
    'adminAddReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminAddSubCategory' : IDL.Func(
        [IDL.Text, CategoryId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveVendor' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveVendorProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
        [],
      ),
    'adminAssignProductToVendor' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteCategory' : IDL.Func(
        [IDL.Text, CategoryId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteFeaturedBlock' : IDL.Func(
        [IDL.Text, FeaturedBlockId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteHeroBanner' : IDL.Func(
        [IDL.Text, HeroBannerId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
    'adminDeleteReview' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'adminDeleteServiceRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'adminDeleteSubCategory' : IDL.Func(
        [IDL.Text, CategoryId, SubCategoryId],
        [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllOrders' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'adminGetCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
    'adminGetServiceRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceRequestPublic)],
        ['query'],
      ),
    'adminListFeaturedBlocks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeaturedBlock)],
        ['query'],
      ),
    'adminListHeroBanners' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HeroBanner)],
        ['query'],
      ),
    'adminListVendorProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VendorProductView)],
        ['query'],
      ),
    'adminListVendorProductsByVendor' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Vec(VendorProductView)],
        ['query'],
      ),
    'adminListVendors' : IDL.Func(
        [IDL.Opt(VendorStatus)],
        [IDL.Vec(VendorSummary)],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'adminRegisterImageHash' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminRejectVendor' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectVendorProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
        [],
      ),
    'adminReorderHeroBanner' : IDL.Func(
        [IDL.Text, HeroBannerId, IDL.Nat],
        [IDL.Variant({ 'ok' : HeroBanner, 'err' : IDL.Text })],
        [],
      ),
    'adminRequestOtp' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetDiscount' : IDL.Func(
        [IDL.Text, ProductId, IDL.Nat],
        [IDL.Opt(Product)],
        [],
      ),
    'adminSetUserAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'adminSuspendVendor' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUnassignProductFromVendor' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateCategory' : IDL.Func(
        [IDL.Text, CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateFeaturedBlock' : IDL.Func(
        [IDL.Text, FeaturedBlockId, FeaturedBlockInput],
        [IDL.Variant({ 'ok' : FeaturedBlock, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateFooterSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(SocialLink)],
        [IDL.Bool],
        [],
      ),
    'adminUpdateHeroAndHowitworks' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(HowItWorksStep)],
        [],
        [],
      ),
    'adminUpdateHeroBanner' : IDL.Func(
        [IDL.Text, HeroBannerId, HeroBannerInput],
        [IDL.Variant({ 'ok' : HeroBanner, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus, IDL.Text],
        [IDL.Opt(OrderPublic)],
        [],
      ),
    'adminUpdatePolicyContent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminUpdateProduct' : IDL.Func(
        [IDL.Text, ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'adminUpdateReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminUpdateServiceRequestStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, ServiceRequestStatus],
        [IDL.Opt(ServiceRequestPublic)],
        [],
      ),
    'adminUpdateServicesAvailability' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'adminUpdateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'logoUrl' : IDL.Opt(IDL.Text),
            'faviconUrl' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'adminUpdateStock' : IDL.Func(
        [IDL.Text, ProductId, IDL.Nat],
        [IDL.Opt(Product)],
        [],
      ),
    'adminUpdateSubCategory' : IDL.Func(
        [IDL.Text, CategoryId, SubCategoryId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Category, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateVendorProductQuantity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateVideoByte' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'adminVerifyKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminVerifyOtp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
    'clearMyCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'orderId' : IDL.Text,
              'currency' : IDL.Text,
              'amount' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getCategoryBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getFeaturedBlock' : IDL.Func(
        [FeaturedBlockId],
        [IDL.Opt(FeaturedBlock)],
        ['query'],
      ),
    'getFooterSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'tagline' : IDL.Text,
            'socialLinks' : IDL.Vec(SocialLink),
            'policyContent' : IDL.Text,
            'aboutContent' : IDL.Text,
            'copyright' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getHeroBanner' : IDL.Func(
        [HeroBannerId],
        [IDL.Opt(HeroBanner)],
        ['query'],
      ),
    'getMyCart' : IDL.Func([], [CartPublic], []),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfilePublic], []),
    'getMyVendorOrders' : IDL.Func(
        [],
        [IDL.Vec(VendorOrderSummary)],
        ['query'],
      ),
    'getMyVendorProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : VendorProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
    'getServicesAvailability' : IDL.Func(
        [],
        [IDL.Record({ 'available' : IDL.Bool, 'message' : IDL.Text })],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'heroSubtitle' : IDL.Text,
            'howitworksSteps' : IDL.Vec(HowItWorksStep),
            'logoUrl' : IDL.Opt(IDL.Text),
            'faviconUrl' : IDL.Opt(IDL.Text),
            'heroTagline' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getVendorForProduct' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VendorSummary)],
        ['query'],
      ),
    'getVendorStatusBySession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VendorStatus)],
        ['query'],
      ),
    'getVideoByte' : IDL.Func(
        [],
        [
          IDL.Record({
            'url' : IDL.Text,
            'title' : IDL.Text,
            'enabled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBestSellers' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listFeaturedBlocks' : IDL.Func([], [IDL.Vec(FeaturedBlock)], ['query']),
    'listHeroBanners' : IDL.Func([], [IDL.Vec(HeroBanner)], ['query']),
    'listNewArrivals' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [ProductListResult], ['query']),
    'listProductsByCategory' : IDL.Func(
        [CategoryId, IDL.Nat, IDL.Nat],
        [ProductListResult],
        ['query'],
      ),
    'processVendorActionToken' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'reject' : IDL.Null, 'approve' : IDL.Null })],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'razorpayTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'registerVendor' : IDL.Func(
        [VendorRegistration],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [CartPublic], []),
    'requestOtp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [ProductListResult],
        ['query'],
      ),
    'submitServiceRequest' : IDL.Func(
        [CreateServiceRequestInput],
        [ServiceRequestPublic],
        [],
      ),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
    'updateMyProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
    'vendorGetMyProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(VendorProductView), 'err' : IDL.Text })],
        [],
      ),
    'vendorSubmitProduct' : IDL.Func(
        [IDL.Text, VendorProductInput],
        [IDL.Variant({ 'ok' : VendorProductView, 'err' : IDL.Text })],
        [],
      ),
    'vendorUpdateProductQuantity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'verifyVendorOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'status' : VendorStatus, 'token' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };