/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserId = IDL.Principal;
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'addresses' : IDL.Vec(Address),
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'addedAt' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const CartPublic = IDL.Record({
  'userId' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});
export const CategoryId = IDL.Nat;
export const ProductInput = IDL.Record({
  'subCategory' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'stock' : IDL.Nat,
  'category' : CategoryId,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'subCategory' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'stock' : IDL.Nat,
  'category' : CategoryId,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'OutForDelivery' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ShipmentUpdate = IDL.Record({
  'status' : OrderStatus,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'productId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'shipmentUpdates' : IDL.Vec(ShipmentUpdate),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'estimatedDelivery' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const CreateOrderInput = IDL.Record({
  'deliveryAddress' : DeliveryAddress,
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'subCategories' : IDL.Vec(IDL.Text),
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'inStockOnly' : IDL.Bool,
  'offset' : IDL.Nat,
  'maxPrice' : IDL.Opt(IDL.Nat),
  'limit' : IDL.Nat,
  'searchTerm' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const ProductListResult = IDL.Record({
  'total' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMyAddress' : IDL.Func([Address], [UserProfilePublic], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
  'adminAddProduct' : IDL.Func([ProductInput], [Product], []),
  'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'adminGetAllOrders' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'adminSetDiscount' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
  'adminSetUserAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'adminUpdateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus, IDL.Text],
      [IDL.Opt(OrderPublic)],
      [],
    ),
  'adminUpdateProduct' : IDL.Func(
      [ProductId, ProductInput],
      [IDL.Opt(Product)],
      [],
    ),
  'adminUpdateStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
  'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
  'clearMyCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getCategoryBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getMyCart' : IDL.Func([], [CartPublic], []),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfilePublic], []),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [ProductListResult], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId, IDL.Nat, IDL.Nat],
      [ProductListResult],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([IDL.Nat], [CartPublic], []),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [ProductListResult],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
  'updateMyProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'addresses' : IDL.Vec(Address),
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'addedAt' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const CartPublic = IDL.Record({
    'userId' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  const CategoryId = IDL.Nat;
  const ProductInput = IDL.Record({
    'subCategory' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'stock' : IDL.Nat,
    'category' : CategoryId,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'subCategory' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'stock' : IDL.Nat,
    'category' : CategoryId,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'OutForDelivery' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ShipmentUpdate = IDL.Record({
    'status' : OrderStatus,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'productId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'shipmentUpdates' : IDL.Vec(ShipmentUpdate),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'estimatedDelivery' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const CreateOrderInput = IDL.Record({
    'deliveryAddress' : DeliveryAddress,
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'subCategories' : IDL.Vec(IDL.Text),
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'inStockOnly' : IDL.Bool,
    'offset' : IDL.Nat,
    'maxPrice' : IDL.Opt(IDL.Nat),
    'limit' : IDL.Nat,
    'searchTerm' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const ProductListResult = IDL.Record({
    'total' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addMyAddress' : IDL.Func([Address], [UserProfilePublic], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
    'adminAddProduct' : IDL.Func([ProductInput], [Product], []),
    'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'adminGetAllOrders' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'adminSetDiscount' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
    'adminSetUserAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'adminUpdateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus, IDL.Text],
        [IDL.Opt(OrderPublic)],
        [],
      ),
    'adminUpdateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'adminUpdateStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
    'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
    'clearMyCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [OrderPublic], []),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getCategoryBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getMyCart' : IDL.Func([], [CartPublic], []),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfilePublic], []),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'isCurrentUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [ProductListResult], ['query']),
    'listProductsByCategory' : IDL.Func(
        [CategoryId, IDL.Nat, IDL.Nat],
        [ProductListResult],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [CartPublic], []),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [ProductListResult],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [CartPublic], []),
    'updateMyProfile' : IDL.Func([UserProfileInput], [UserProfilePublic], []),
  });
};

export const init = ({ IDL }) => { return []; };