/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export interface CartItem {
  'productId' : bigint,
  'addedAt' : bigint,
  'quantity' : bigint,
}
export interface CartPublic {
  'userId' : Principal,
  'updatedAt' : bigint,
  'items' : Array<CartItem>,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
  'description' : string,
  'imageUrl' : string,
  'subCategories' : Array<string>,
}
export type CategoryId = bigint;
export interface CreateOrderInput {
  'deliveryAddress' : DeliveryAddress,
  'items' : Array<{ 'productId' : bigint, 'quantity' : bigint }>,
}
export interface CreateServiceRequestInput {
  'userName' : string,
  'serviceType' : ServiceType,
  'recipientPhone' : [] | [string],
  'description' : string,
  'userPhone' : string,
  'isRequestForSelf' : boolean,
  'preferredDate' : string,
  'preferredTime' : string,
  'recipientAddress' : [] | [string],
  'recipientName' : [] | [string],
}
export interface DeliveryAddress {
  'city' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'discountPercent' : bigint,
  'productId' : bigint,
  'imageUrl' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'shipmentUpdates' : Array<ShipmentUpdate>,
  'userId' : Principal,
  'createdAt' : bigint,
  'estimatedDelivery' : [] | [bigint],
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'OutForDelivery' : null };
export interface Product {
  'id' : ProductId,
  'subCategory' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'stock' : bigint,
  'category' : CategoryId,
  'brand' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'inStockOnly' : boolean,
  'offset' : bigint,
  'maxPrice' : [] | [bigint],
  'limit' : bigint,
  'searchTerm' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export interface ProductInput {
  'subCategory' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'stock' : bigint,
  'category' : CategoryId,
  'brand' : string,
  'rating' : bigint,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductListResult {
  'total' : bigint,
  'products' : Array<Product>,
}
export interface ServiceRequestPublic {
  'id' : bigint,
  'status' : ServiceRequestStatus,
  'userName' : string,
  'serviceType' : ServiceType,
  'userId' : string,
  'recipientPhone' : [] | [string],
  'submittedAt' : bigint,
  'description' : string,
  'userPhone' : string,
  'lastUpdatedAt' : bigint,
  'isRequestForSelf' : boolean,
  'preferredDate' : string,
  'preferredTime' : string,
  'recipientAddress' : [] | [string],
  'recipientName' : [] | [string],
}
export type ServiceRequestStatus = { 'New' : null } |
  { 'Contacted' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export type ServiceType = { 'Ambulance' : null } |
  { 'FoodDelivery' : null } |
  { 'Taxi' : null } |
  { 'SchoolAdmissions' : null } |
  { 'Medicines' : null } |
  { 'Gifting' : null } |
  { 'FuneralServices' : null } |
  { 'Tourism' : null } |
  { 'Doctors' : null } |
  { 'VideoConferencing' : null } |
  { 'EventManagement' : null } |
  { 'WeddingsAnniversaries' : null } |
  { 'Other' : null };
export interface ShipmentUpdate {
  'status' : OrderStatus,
  'message' : string,
  'timestamp' : bigint,
}
export type UserId = Principal;
export interface UserProfileInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'addresses' : Array<Address>,
  'isAdmin' : boolean,
  'phone' : string,
}
export interface _SERVICE {
  'addMyAddress' : ActorMethod<[Address], UserProfilePublic>,
  'addToCart' : ActorMethod<[bigint, bigint], CartPublic>,
  'adminAddProduct' : ActorMethod<[ProductInput], Product>,
  'adminDeleteProduct' : ActorMethod<[ProductId], boolean>,
  'adminDeleteServiceRequest' : ActorMethod<[bigint], boolean>,
  'adminGetAllOrders' : ActorMethod<[bigint, bigint], Array<OrderPublic>>,
  'adminGetServiceRequests' : ActorMethod<[], Array<ServiceRequestPublic>>,
  'adminSetDiscount' : ActorMethod<[ProductId, bigint], [] | [Product]>,
  'adminSetUserAdmin' : ActorMethod<[Principal, boolean], boolean>,
  'adminUpdateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus, string],
    [] | [OrderPublic]
  >,
  'adminUpdateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
  'adminUpdateServiceRequestStatus' : ActorMethod<
    [bigint, ServiceRequestStatus],
    [] | [ServiceRequestPublic]
  >,
  'adminUpdateStock' : ActorMethod<[ProductId, bigint], [] | [Product]>,
  'claimAdminIfFirst' : ActorMethod<[], boolean>,
  'clearMyCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[CreateOrderInput], OrderPublic>,
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  'getCategoryBySlug' : ActorMethod<[string], [] | [Category]>,
  'getMyCart' : ActorMethod<[], CartPublic>,
  'getMyOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getMyProfile' : ActorMethod<[], UserProfilePublic>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'isCurrentUserAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProducts' : ActorMethod<[ProductFilter], ProductListResult>,
  'listProductsByCategory' : ActorMethod<
    [CategoryId, bigint, bigint],
    ProductListResult
  >,
  'removeFromCart' : ActorMethod<[bigint], CartPublic>,
  'searchProducts' : ActorMethod<[string, bigint, bigint], ProductListResult>,
  'submitServiceRequest' : ActorMethod<
    [CreateServiceRequestInput],
    ServiceRequestPublic
  >,
  'updateCartItem' : ActorMethod<[bigint, bigint], CartPublic>,
  'updateMyProfile' : ActorMethod<[UserProfileInput], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];