/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShipmentUpdate {
    status: OrderStatus;
    message: string;
    timestamp: bigint;
}
export interface ProductInput {
    subCategory: string;
    title: string;
    imageUrls: Array<string>;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    stock: bigint;
    category: CategoryId;
    brand: string;
    rating: bigint;
    price: bigint;
    reviewCount: bigint;
}
export interface Category {
    id: CategoryId;
    name: string;
    slug: string;
    description: string;
    imageUrl: string;
    subCategories: Array<string>;
}
export interface CartItem {
    productId: bigint;
    addedAt: bigint;
    quantity: bigint;
}
export interface ProductListResult {
    total: bigint;
    products: Array<Product>;
}
export interface Address {
    city: string;
    name: string;
    line1: string;
    line2: string;
    state: string;
    isDefault: boolean;
    phone: string;
    pincode: string;
}
export interface OrderItem {
    title: string;
    discountPercent: bigint;
    productId: bigint;
    imageUrl: string;
    quantity: bigint;
    price: bigint;
}
export interface OrderPublic {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    shipmentUpdates: Array<ShipmentUpdate>;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery?: bigint;
    updatedAt: bigint;
    totalAmount: bigint;
    items: Array<OrderItem>;
}
export interface ProductFilter {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    offset: bigint;
    maxPrice?: bigint;
    limit: bigint;
    searchTerm?: string;
    minPrice?: bigint;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    addresses: Array<Address>;
    isAdmin: boolean;
    phone: string;
}
export type UserId = Principal;
export interface CreateOrderInput {
    deliveryAddress: DeliveryAddress;
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
}
export type CategoryId = bigint;
export type ProductId = bigint;
export interface DeliveryAddress {
    city: string;
    name: string;
    line1: string;
    line2: string;
    state: string;
    phone: string;
    pincode: string;
}
export interface CartPublic {
    userId: Principal;
    updatedAt: bigint;
    items: Array<CartItem>;
}
export interface UserProfileInput {
    name: string;
    email: string;
    phone: string;
}
export interface Product {
    id: ProductId;
    subCategory: string;
    title: string;
    imageUrls: Array<string>;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    isActive: boolean;
    updatedAt: bigint;
    stock: bigint;
    category: CategoryId;
    brand: string;
    rating: bigint;
    price: bigint;
    reviewCount: bigint;
}
export type OrderId = bigint;
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Processing = "Processing",
    Shipped = "Shipped",
    OutForDelivery = "OutForDelivery"
}
export interface backendInterface {
    addMyAddress(address: Address): Promise<UserProfilePublic>;
    addToCart(productId: bigint, quantity: bigint): Promise<CartPublic>;
    adminAddProduct(input: ProductInput): Promise<Product>;
    adminDeleteProduct(id: ProductId): Promise<boolean>;
    adminGetAllOrders(limit: bigint, offset: bigint): Promise<Array<OrderPublic>>;
    adminSetDiscount(id: ProductId, discountPercent: bigint): Promise<Product | null>;
    adminSetUserAdmin(targetUser: Principal, adminStatus: boolean): Promise<boolean>;
    adminUpdateOrderStatus(orderId: OrderId, newStatus: OrderStatus, message: string): Promise<OrderPublic | null>;
    adminUpdateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
    adminUpdateStock(id: ProductId, newStock: bigint): Promise<Product | null>;
    claimAdminIfFirst(): Promise<boolean>;
    clearMyCart(): Promise<void>;
    createOrder(input: CreateOrderInput): Promise<OrderPublic>;
    getCategory(id: CategoryId): Promise<Category | null>;
    getCategoryBySlug(slug: string): Promise<Category | null>;
    getMyCart(): Promise<CartPublic>;
    getMyOrders(): Promise<Array<OrderPublic>>;
    getMyProfile(): Promise<UserProfilePublic>;
    getOrder(orderId: OrderId): Promise<OrderPublic | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    isCurrentUserAdmin(): Promise<boolean>;
    listCategories(): Promise<Array<Category>>;
    listProducts(filter: ProductFilter): Promise<ProductListResult>;
    listProductsByCategory(categoryId: CategoryId, limit: bigint, offset: bigint): Promise<ProductListResult>;
    removeFromCart(productId: bigint): Promise<CartPublic>;
    searchProducts(term: string, limit: bigint, offset: bigint): Promise<ProductListResult>;
    updateCartItem(productId: bigint, quantity: bigint): Promise<CartPublic>;
    updateMyProfile(input: UserProfileInput): Promise<UserProfilePublic>;
}
import type { Category as _Category, CategoryId as _CategoryId, DeliveryAddress as _DeliveryAddress, OrderId as _OrderId, OrderItem as _OrderItem, OrderPublic as _OrderPublic, OrderStatus as _OrderStatus, Product as _Product, ProductFilter as _ProductFilter, ShipmentUpdate as _ShipmentUpdate } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMyAddress(arg0: Address): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addMyAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMyAddress(arg0);
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async adminAddProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddProduct(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminGetAllOrders(arg0: bigint, arg1: bigint): Promise<Array<OrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllOrders(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllOrders(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetDiscount(arg0: ProductId, arg1: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetDiscount(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetDiscount(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetUserAdmin(arg0: Principal, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUserAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUserAdmin(arg0, arg1);
            return result;
        }
    }
    async adminUpdateOrderStatus(arg0: OrderId, arg1: OrderStatus, arg2: string): Promise<OrderPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateStock(arg0: ProductId, arg1: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStock(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStock(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimAdminIfFirst(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminIfFirst();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminIfFirst();
            return result;
        }
    }
    async clearMyCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyCart();
            return result;
        }
    }
    async createOrder(arg0: CreateOrderInput): Promise<OrderPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return from_candid_OrderPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return from_candid_OrderPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: CategoryId): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryBySlug(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBySlug(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBySlug(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCart(): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCart();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<OrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCurrentUserAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCurrentUserAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCurrentUserAdmin();
            return result;
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listProducts(arg0: ProductFilter): Promise<ProductListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listProductsByCategory(arg0: CategoryId, arg1: bigint, arg2: bigint): Promise<ProductListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async removeFromCart(arg0: bigint): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string, arg1: bigint, arg2: bigint): Promise<ProductListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCartItem(arg0: bigint, arg1: bigint): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return result;
        }
    }
    async updateMyProfile(arg0: UserProfileInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return result;
        }
    }
}
function from_candid_OrderPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderPublic): OrderPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentUpdate_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentUpdate): ShipmentUpdate {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderPublic]): OrderPublic | null {
    return value.length === 0 ? null : from_candid_OrderPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    deliveryAddress: _DeliveryAddress;
    shipmentUpdates: Array<_ShipmentUpdate>;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery: [] | [bigint];
    updatedAt: bigint;
    totalAmount: bigint;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    shipmentUpdates: Array<ShipmentUpdate>;
    userId: Principal;
    createdAt: bigint;
    estimatedDelivery?: bigint;
    updatedAt: bigint;
    totalAmount: bigint;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        shipmentUpdates: from_candid_vec_n6(_uploadFile, _downloadFile, value.shipmentUpdates),
        userId: value.userId,
        createdAt: value.createdAt,
        estimatedDelivery: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.estimatedDelivery)),
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    message: string;
    timestamp: bigint;
}): {
    status: OrderStatus;
    message: string;
    timestamp: bigint;
} {
    return {
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    OutForDelivery: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Cancelled" in value ? OrderStatus.Cancelled : "Processing" in value ? OrderStatus.Processing : "Shipped" in value ? OrderStatus.Shipped : "OutForDelivery" in value ? OrderStatus.OutForDelivery : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderPublic>): Array<OrderPublic> {
    return value.map((x)=>from_candid_OrderPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShipmentUpdate>): Array<ShipmentUpdate> {
    return value.map((x)=>from_candid_ShipmentUpdate_n7(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    offset: bigint;
    maxPrice?: bigint;
    limit: bigint;
    searchTerm?: string;
    minPrice?: bigint;
}): {
    categoryId: [] | [_CategoryId];
    inStockOnly: boolean;
    offset: bigint;
    maxPrice: [] | [bigint];
    limit: bigint;
    searchTerm: [] | [string];
    minPrice: [] | [bigint];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        inStockOnly: value.inStockOnly,
        offset: value.offset,
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        limit: value.limit,
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    OutForDelivery: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Processing ? {
        Processing: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.OutForDelivery ? {
        OutForDelivery: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
